-- CICLO
DELETE FROM ciclo;
INSERT INTO CICLO (nombreciclo, inicio, fin, estadociclo, inicioperiodoclase, finperiodoclase)
    VALUES ("CICLO I", "2020/02/16", "2020/02/16", 1, "2020/02/16", "2020/02/16");
INSERT INTO CICLO (nombreciclo, inicio, fin, estadociclo, inicioperiodoclase, finperiodoclase)
    VALUES ("CICLO II", "2020/07/25", "2020/07/25", 0, "2020/07/25", "2020/07/25");

-- TIPO GRUPO 
DELETE FROM TIPOGRUPO;
INSERT INTO TIPOGRUPO (nombretipogrupo) VALUES ("Teórico");
INSERT INTO TIPOGRUPO (nombretipogrupo) VALUES ("Laboratorio");
INSERT INTO TIPOGRUPO (nombretipogrupo) VALUES ("Discusión");

-- DIA 
DELETE FROM DIA;
INSERT INTO DIA (nombredia) VALUES ("Sunday");
INSERT INTO DIA (nombredia) VALUES ("Lunes");
INSERT INTO DIA (nombredia) VALUES ("Martes");
INSERT INTO DIA (nombredia) VALUES ("Miércoles");
INSERT INTO DIA (nombredia) VALUES ("Jueves");
INSERT INTO DIA (nombredia) VALUES ("Viernes");
INSERT INTO DIA (nombredia) VALUES ("Sábado");

-- UNIDAD 
DELETE FROM UNIDAD;
INSERT INTO UNIDAD (nombreent, descripcionent, prioridad)
    VALUES ("EISI", "Escuela de Ingeniería de Sistemas Informáticos", 2);
INSERT INTO UNIDAD (nombreent, descripcionent, prioridad)
    VALUES ("UCB", "Unidad de Ciencias Básicas", 1);

-- MATERIA 
DELETE FROM MATERIA;
INSERT INTO MATERIA (codmateria, nombremat, masiva, idunidad)
    VALUES ("MAT115", "Matemáticas 1", 1, 2);
INSERT INTO MATERIA (codmateria, nombremat, masiva, idunidad)
    VALUES ("PRN115", "Programación para Dispositivos Móviles", 2, 1);
INSERT INTO MATERIA (codmateria, nombremat, masiva, idunidad)
    VALUES ("FIR115", "Física I", 1, 2);
INSERT INTO MATERIA (codmateria, nombremat, masiva, idunidad)
    VALUES ("TSI115", "Teoría de Sistemas", 2, 1);

-- CICLO MATERIA 
DELETE FROM CICLOMATERIA;
INSERT INTO CICLOMATERIA (idciclo, codmateria) VALUES (1, "MAT115");
INSERT INTO CICLOMATERIA (idciclo, codmateria) VALUES (1, "PRN115");
INSERT INTO CICLOMATERIA (idciclo, codmateria) VALUES (2, "IEC115");
INSERT INTO CICLOMATERIA (idciclo, codmateria) VALUES (2, "TSI115");

-- OPCIONCRUD
DELETE FROM OPCIONCRUD;
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IAU','Insertar acceso usuario',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EAU','Editar acceso usuario',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DAU','Eliminar acceso usuario',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CAU','Consultar acceso usuario',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ICL','Insertar ciclo',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ECL','Editar ciclo',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DCL','Eliminar cilo',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CCL','Consultar ciclo',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ICM','Insertar ciclo-materia',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ECM','Editar ciclo-materia',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DCM','Eliminar ciclo-materia',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CCM','Consultar ciclo-materia',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ICO','Insertar coordinación',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ECO','Editar coordinación',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DCO','Eliminar coordinación',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CCO','Consultar coordinación',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IDR','Insertar detalle reserva',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EDR','Editar detalle reserva',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DDR','Eliminar detalle reserva',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CDR','Consultar detalle reserva',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IDI','Insertar día',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EDI','Editar día',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DDI','Eliminar día',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CDI','Consultar día',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IEN','Insertar encargado',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EEN','Editar encargado',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DEN','Eliminar encargado',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CEN','Consultar encargado',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IEE','Insertar evento especial',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EEE','Editar evento especial',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DEE','Eliminar evento especial',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CEE','Consultar evento especial',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IFE','Insertar feriado',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EFI','Editar feriado',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DFE','Eliminar feriado',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CFE','Consultar feriado',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IGR','Insertar grupo',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EGR','Editar grupo',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DGR','Eliminar grupo',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CGR','Consultar grupo',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IHO','Insertar horario',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EHO','Editar horario',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DHO','Eliminar horario',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CHO','Consultar horario',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ILO','Insertar local',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ELO','Editar local',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DLO','Eliminar local',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CLO','Consultar local',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IMA','Insertar materia',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EMA','Editar materia',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DMA','Eliminar materia',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CMA','Consultar materia',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ISO','Insertar solicitud',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ESO','Editar solicitud',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DSO','Eliminar solicitud',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CSO','Consultar solicitud',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ITG','Insertar tipo grupo',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ETG','Editar tipo grupo',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DTG','Eliminar tipo grupo',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CTG','Consultar tipo grupo',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ITL','Insertar tipo local',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('ETL','Editar tipo local',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DTL','Eliminar tipo local',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CTL','Consultar tipo local',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IUS','Insertar usuario',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EUS','Editar usuario',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DUS','Eliminar usuario',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CUS','Consultar usuario',4);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('IUN','Insertar unidad',1);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('EUN','Editar unidad',2);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('DUN','Eliminar unidad',3);
INSERT INTO OPCIONCRUD(IDOPCION,DESOPCION,NUMCRUD) VALUES ('CUN','Consultar unidad',4);

-- USUARIO
DELETE FROM USUARIO;
INSERT INTO USUARIO(IDUSUARIO,IDUNIDAD,NOMBREUSUARIO,CLAVEUSUARIO,NOMBREPERSONAL,APELLIDOPERSONAL,CORREOPERSONAL) VALUES ('0A',0,'admin','admin','Administrador','App','administrador@admin.com');

-- ACCESOUSUARIO
DELETE FROM ACCESOUSUARIO;
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IAU','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EAU','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DAU','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CAU','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ICL','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ECL','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DCL','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CCL','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ICM','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ECM','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DCM','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CCM','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ICO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ECO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DCO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CCO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IDR','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EDR','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DDR','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CDR','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IDI','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EDI','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DDI','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CDI','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IEN','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EEN','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DEN','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CEN','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IEE','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EEE','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DEE','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CEE','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IFE','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EFI','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DFE','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CFE','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IGR','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EGR','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DGR','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CGR','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IHO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EHO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DHO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CHO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ILO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ELO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DLO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CLO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IMA','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EMA','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DMA','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CMA','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ISO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ESO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DSO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CSO','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ITG','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ETG','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DTG','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CTG','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ITL','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('ETL','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DTL','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CTL','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IUS','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EUS','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DUS','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CUS','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('IUN','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('EUN','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('DUN','0A');
INSERT INTO ACCESOUSUARIO(IDOPCION,IDUSUARIO) VALUES ('CUN','0A');
